services:
  backend:
    image: box-factory-api
    build:
      context: .
      dockerfile: BoxFactoryAPI/Dockerfile
    ports:
      - "5133:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__BoxFactoryDatabase=Host=db;Database=BoxFactoryDB;Username=boxfactoryuser;Password=boxfactorypassword
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      - POSTGRES_USER=boxfactoryuser
      - POSTGRES_PASSWORD=boxfactorypassword
      - POSTGRES_DB=BoxFactoryDB
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "BoxFactoryDB" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  frontend:
    image: box-factory-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      backend:
        condition: service_healthy
