name: Backend tests and code quality checks
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    # SonarQube requires JDK 17
#    - name: Set up JDK 17
#      uses: actions/setup-java@v5
#      with:
#        java-version: 17
#        distribution: 'zulu' # Alternative distribution options are available.
        
#    - name: Cache SonarQube Cloud packages
#      uses: actions/cache@v5
#      with:
#        path: ~\sonar\cache
#        key: ${{ runner.os }}-sonar
#        restore-keys: ${{ runner.os }}-sonar
#        
#    - name: Cache SonarQube Cloud scanner
#      id: cache-sonar-scanner
#      uses: actions/cache@v4
#      with:
#        path: ${{ runner.temp }}\scanner
#        key: ${{ runner.os }}-sonar-scanner
#        restore-keys: ${{ runner.os }}-sonar-scanner

    - name: Set up .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        
    - name: Restore dotnet tools
      run: dotnet tool restore
      
    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin /k:"${{ github.repository_owner }}_${{ github.event.repository.name }}" /o:"${{ github.repository_owner }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        dotnet build <path to project file or .sln file>
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Run Unit Tests
      run: dotnet test "Core.UnitTests/Core.UnitTests.csproj" --logger:trx --collect:"XPlat Code Coverage"

    - name: Run Cucumber tests
      run: dotnet test "BoxFactory.BDDTests/BoxFactory.BDDTests.csproj" --logger:trx --collect:"XPlat Code Coverage"

    - name: Run Integration Tests
      run: dotnet test "BoxFactory.IntegrationTests/BoxFactory.IntegrationTests.csproj" --logger:trx --collect:"XPlat Code Coverage"
