name: Backend tests and code quality checks
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
        
    - name: Restore dotnet tools
      run: dotnet tool restore
      
    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        dotnet sonarscanner begin \
          /k:"${{ github.repository_owner }}_${{ github.event.repository.name }}" \
          /o:"${{ github.repository_owner }}" \
          /d:sonar.token="$SONAR_TOKEN" \
          /d:sonar.cs.vstest.reportsPaths="**/*.trx" \
          /d:sonar.cs.opencover.reportsPaths="coverage.*.xml"
        
        dotnet build --no-incremental
        
        dotnet coverlet ./Core.UnitTests/bin/Debug/net10.0/Core.UnitTests.dll \
          --target "dotnet" \
          --targetargs "test ./Core.UnitTests/Core.UnitTests.csproj --no-build --logger:trx" \
          -f=opencover \
          -o="coverage.core.xml"
        
        dotnet coverlet ./BoxFactory.BDDTests/bin/Debug/net10.0/BoxFactory.BDDTests.dll \
          --target "dotnet" \
          --targetargs "test ./BoxFactory.BDDTests/BoxFactory.BDDTests.csproj --no-build --logger:trx" \
          -f=opencover \
          -o="coverage.bdd.xml"
        
        dotnet coverlet ./BoxFactory.IntegrationTests/bin/Debug/net10.0/BoxFactory.IntegrationTests.dll \
          --target "dotnet" \
          --targetargs "test ./BoxFactory.IntegrationTests/BoxFactory.IntegrationTests.csproj --no-build --logger:trx" \
          -f=opencover \
          -o="coverage.integration.xml"
        
        dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
